apply plugin: 'org.springframework.boot'



dependencies {
	implementation project(':consumer')
	implementation 'software.amazon.awssdk:sts'
	implementation project(':sqs-sender')
	implementation project(':metrics')
	implementation project(':secutiry')
	implementation project(':rest-consumer')
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation project(':reactive-web')
	//implementation project(':kafka-consumer')
	implementation 'org.reactivecommons.utils:object-mapper:0.1.0'
	implementation project(':r2dbc-postgresql')
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.slf4j:slf4j-api:2.0.17'
    implementation 'org.apache.logging.log4j:log4j-slf4j2-impl:2.21.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.21.1'
    implementation 'org.apache.logging.log4j:log4j-api:2.21.1'

    implementation 'org.springframework.boot:spring-boot-starter'
    runtimeOnly('org.springframework.boot:spring-boot-devtools')
    testImplementation 'com.tngtech.archunit:archunit:1.4.1'
    testImplementation 'com.fasterxml.jackson.core:jackson-databind'
}

configurations {
    all {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
        exclude group: 'ch.qos.logback', module: 'logback-classic'
    }
}

tasks.register('explodedJar', Copy) {
    with jar
    into layout.buildDirectory.dir("exploded")
}

jar {
    // To disable the *-plain.jar
    enabled = false
}

bootJar {
    // Sets output jar name
    archiveFileName = "${project.getParent().getName()}.${archiveExtension.get()}"
}